version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      frontend:
        patterns: ['*']
    ignore:
      - dependency-name: typescript
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 10

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
      day: monday
    groups:
      rust:
        patterns: ['*']
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
